# Generated by Django 5.2.4 on 2025-07-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatagoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('originalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Shopkart.catagorymodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
