# Generated by Django 5.2.4 on 2025-07-04 11:54

import Shopkart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopkart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Shopkart.models.getFileName),
        ),
    ]
